name: Build Wind OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Install Saf UEFI Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm xorriso mtools grub-common \
                               grub-pc grub-pc-bin \
                               grub-efi-ia32-bin grub-efi-amd64-bin \
                               gcc gcc-multilib

    - name: Build ISO via Script
      run: |
        chmod +x build.sh
        set +e
        bash build.sh
        exit 0

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windos-iso-package
        path: windos.iso
        if-no-files-found: error
