name: Sky-Core-OS Auto-Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib

      - name: Fix Makefile Tab Issue
        run: |
          # Bu komut, Makefile içindeki boşlukları (8 boşluk) TAB ile değiştirir
          sed -i 's/        /\t/g' Makefile

      - name: Build OS
        run: |
          make clean
          make all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kernel.bin
            windos.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
