name: Build Wind OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Paketleri Sessiz ve Zorunlu Kur (Hayat Kurtaran Adım)
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq nasm xorriso mtools grub-common grub-pc grub-pc-bin grub-efi-ia32-bin grub-efi-amd64-bin gcc gcc-multilib

    - name: ISO'yu Derle
      run: |
        chmod +x build.sh
        bash build.sh

    - name: ISO Dosyasını Artifact Olarak Yükle
      uses: actions/upload-artifact@v4
      with:
        name: windos-iso-package
        path: windos.iso
        if-no-files-found: error
